#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bashlex
Version  : 0.12
Release  : 1
URL      : https://files.pythonhosted.org/packages/e6/83/8f35a0a430908e5c964fbf31a8e46fbac125d1bbf066a1e26110c618a3ff/bashlex-0.12.tar.gz
Source0  : https://files.pythonhosted.org/packages/e6/83/8f35a0a430908e5c964fbf31a8e46fbac125d1bbf066a1e26110c618a3ff/bashlex-0.12.tar.gz
Summary  : Python parser for bash
Group    : Development/Tools
License  : GPL-3.0+
Requires: bashlex-python = %{version}-%{release}
Requires: bashlex-python3 = %{version}-%{release}
Requires: enum34
BuildRequires : buildreq-distutils3
BuildRequires : enum34

%description
No detailed description available

%package python
Summary: python components for the bashlex package.
Group: Default
Requires: bashlex-python3 = %{version}-%{release}

%description python
python components for the bashlex package.


%package python3
Summary: python3 components for the bashlex package.
Group: Default
Requires: python3-core

%description python3
python3 components for the bashlex package.


%prep
%setup -q -n bashlex-0.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548338727
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
